name: download-and-run

on:
  repository_dispatch:
    types: [altas-update]
  workflow_dispatch:

jobs:
  build:
    name: Download and run
    env:
      MY_SECRET: ${{ secrets.commit_secret }}
      USER_NAME: githubaction
      USER_EMAIL: githubaction@fake.com
      PUBLISH_DIR: ./output_raw
      GH_PAGES_BRANCH: gh-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: |
          yarn install

      - name: Download and run
        run: |
          yarn download:assets
          ls -al artifacts
          yarn start

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: origin-${{ env.PUBLISH_DIR }}
          clean: false

      - name: Commit files
        run: |
          cp -r ${{ env.PUBLISH_DIR }}/* origin-${{ env.PUBLISH_DIR }}
          cd origin-${{ env.PUBLISH_DIR }}
          git config --global user.name ${{ env.USER_NAME }}
          git config --global user.email ${{ env.USER_EMAIL }}
          git add --all
          git diff-index --quiet HEAD || git commit -m "Update atlas images"
          git push origin HEAD
